[supervisord]
nodaemon=true
user=root

[program:postgresql]
user=postgres
command=/usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main -c config_file=/etc/postgresql/14/main/postgresql.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/postgresql.err.log
stdout_logfile=/var/log/postgresql.out.log
priority=10

[program:flask]
directory=/app
command=python3 app.py
autostart=true
autorestart=true
stderr_logfile=/var/log/flask.err.log
stdout_logfile=/var/log/flask.out.log
priority=20
environment=FLASK_APP="app.py",FLASK_ENV="development"
