-- Migration: Add title column to session storage
-- Date: 2025-12-02
-- Description: Adds support for session titles generated by tinyollama

-- Session Storage Architecture:
-- 1. PRIMARY STORAGE: Sessions are stored in Redis (cli:session:<id>) for fast access
--    - Redis stores: session_id, title, history, start_time, saved_at, metadata
--    - Sessions persist indefinitely in Redis (no TTL)
--
-- 2. RATINGS STORAGE: PostgreSQL conversation_ratings table tracks prompt ratings
--    - The session_title column links ratings to their session context
--    - This enables analytics on session-based user satisfaction
--
-- 3. FUTURE CONSIDERATIONS:
--    - May add a dedicated sessions table in PostgreSQL for long-term archival
--    - Session data can be migrated from Redis to PostgreSQL for historical analysis

-- Add title column to conversation_ratings (which tracks session context)
ALTER TABLE conversation_ratings
ADD COLUMN IF NOT EXISTS session_title TEXT;

-- Add comment for documentation
COMMENT ON COLUMN conversation_ratings.session_title IS 'Auto-generated session title from tinyollama based on first prompt';

-- Create index on session_title for efficient title-based queries
CREATE INDEX IF NOT EXISTS idx_conversation_ratings_session_title
ON conversation_ratings(session_title);
