-- Migration: Add title column to session storage
-- Date: 2025-12-02
-- Description: Adds support for session titles generated by tinyollama

-- Note: Sessions are primarily stored in Redis, but this migration
-- prepares the PostgreSQL schema for potential future session storage.

-- Add title column to conversation_ratings (which tracks session context)
ALTER TABLE conversation_ratings
ADD COLUMN IF NOT EXISTS session_title TEXT;

-- Add comment for documentation
COMMENT ON COLUMN conversation_ratings.session_title IS 'Auto-generated session title from tinyollama based on first prompt';

-- Create index on session_title for efficient title-based queries
CREATE INDEX IF NOT EXISTS idx_conversation_ratings_session_title
ON conversation_ratings(session_title);
